[common]
	[common.worldGenerator]
		enableDistantGeneration = true
    distantGeneratorMode = "PRE_EXISTING_ONLY"
    
[client]
	[client.advanced]
		[client.advanced.autoUpdater]
      enableAutoUpdater = false