name = "MRRSPack.Dione"
author = "Kostek001"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34453c1bffcfbf680a59b1ac7d33f45afacd862573142e015cd02bc2daf6175f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.210"
