name = "MRRSPack Rhea"
author = "Kostek001"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8a607019919eabb8af324be7316fd5cc672d9b4c0b4aa7da8744bbae96a6e4a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
