name = "MRRSPack"
author = "Kostek001"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c737b17d170c28990116b50bc1a4eeaa30eadb6fc0fb3276cac0680646c0133"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
