name = "MRRSPack.Dione"
author = "Kostek001"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e54f4e4aeee8bedf018563021091b927e442bbe68f4209f055d328e33bb185c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.210"
