name = "MRRSPack"
author = "Kostek001"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4b264e5f2d75d4a188b0bbbaa9c2bc63331b8a664e6290c786e295ed26dec0a"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
