name = "MRRSPack"
author = "Kostek001"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9348cf17251e5828af7f533c3b3b8d5e7eb41db220867af0d2e80dc43834f2f9"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
