name = "MRRSPack"
author = "Kostek001"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aae436e00b87c72e3e661b33a9b96fd2691f0b689c269250696f6bff1423e85f"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
