name = "MRRSPack"
author = "Kostek001"
version = "1.0.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "838458601fa3268e5b9d458f928584eb7f92a9ed04f70863a05a8634dc7a426f"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
